name: Build APK - Telefonía Personal

on:
  push:
    branches:
      - main  # Ejecutar el flujo de trabajo cuando se haga push a la rama principal
  pull_request:
    branches:
      - main  # También cuando se haga un PR a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos un runner de Ubuntu
    
    steps:
      # Paso 1: Configuración de herramientas de Android SDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'  # Usamos AdoptOpenJDK

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33  # Usamos Android 13 como SDK objetivo
          build-tools: 33.0.0  # Herramientas de construcción
          ndk: 21.4.7075529  # NDK si es necesario para bibliotecas nativas

      # Paso 2: Clonar el repositorio
      - name: Check out the repository
        uses: actions/checkout@v3

      # Paso 3: Configuración de Gradle
      - name: Set up Gradle Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK with Gradle
        run: |
          ./gradlew clean assembleRelease  # Limpiamos y compilamos la versión de release

      # Paso 4: Firma del APK
      - name: Sign APK
        run: |
          KEYSTORE_PASSWORD=telefoniaPersonal123
          KEY_ALIAS=telefoniakey
          KEYSTORE_PATH=./keystore/telefoniaPersonal.keystore
          APK_PATH=./app/build/outputs/apk/release/app-release-unsigned.apk
          
          # Firmar el APK
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA-256 -keystore $KEYSTORE_PATH -storepass $KEYSTORE_PASSWORD -keypass $KEYSTORE_PASSWORD $APK_PATH $KEY_ALIAS
          # Añadir APK alineado
          zipalign -v 4 $APK_PATH ./app/build/outputs/apk/release/app-release-signed.apk

      # Paso 5: Subir el APK
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: telefonia-personal-apk
          path: ./app/build/outputs/apk/release/app-release-signed.apk
